export DBHOST="afr-aho-mariadb-svr.mariadb.database.azure.com"
export DBUSER="afroahodbadmin@afr-aho-mariadb-svr"
export DBNAME="aho_database"
export DBPASS="AFr578!%$2020"
export SSL_CERT_FILE="/home/site/cert/BaltimoreCyberTrustRoot.crt.pem"
