$Env:DBHOST = "af-aho-mariadb-svr.mariadb.database.azure.com"
$Env:DBUSER = "afroahodbadmin@af-aho-mariadb-svr"
$Env:DBNAME = "aho_database"
$Env:DBPASS = "AFr578!%$2020"
$Env:SSL_CERT_FILE = "/sites/cert/BaltimoreCyberTrustRoot.crt.pem"
