# Generated by Django 2.2.12 on 2021-03-22 05:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgfacilityownership',
            name='location',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocationCodes', verbose_name='Owner Country'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='stghealthfacility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude'),
        ),
    ]
