# Generated by Django 2.1.2 on 2021-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0012_auto_20201024_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthfacilitytranslation',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='stghealthfacilitytranslation',
            name='year_established',
            field=models.IntegerField(blank=True, default=2021, null=True, verbose_name='Year Established'),
        ),
    ]
