# Generated by Django 2.2.12 on 2021-03-18 07:29

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AhoDoamain_Lookup',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator_name', models.CharField(max_length=500, verbose_name='Indicator Name')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Indicator Code')),
                ('domain_name', models.CharField(blank=True, max_length=230, verbose_name='Theme')),
                ('domain_level', models.IntegerField(verbose_name='Theme Level')),
            ],
            options={
                'verbose_name': 'Theme Lookup',
                'verbose_name_plural': 'Themes Lookup',
                'db_table': 'aho_domain_lookup',
                'ordering': ('indicator_name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StgIndicator',
            fields=[
                ('indicator_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('afrocode', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Regional Code')),
                ('gen_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Global Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': '  Indicators',
                'db_table': 'stg_indicator',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorDomain',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('level', models.SmallIntegerField(choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4'), (5, 'level 5'), (6, 'level 6')], default=1, verbose_name='Theme Level')),
                ('code', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('indicators', models.ManyToManyField(blank=True, db_table='stg_indicator_domain_members', to='indicators.StgIndicator', verbose_name='Indicators')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicatorDomain', verbose_name='Parent Theme')),
            ],
            options={
                'verbose_name': 'Indicator Theme',
                'verbose_name_plural': ' Indicator Themes',
                'db_table': 'stg_indicator_domain',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorReference',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Indicator Reference',
                'verbose_name_plural': 'Indicator References',
                'db_table': 'stg_indicator_reference',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgNarrative_Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Narrative Type',
                'verbose_name_plural': 'Narrative Types',
                'db_table': 'stg_narrative_type',
                'ordering': ('translations__name',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IndicatorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Data Grid Form',
                'verbose_name_plural': '   Multi-records Grid',
                'managed': False,
                'proxy': True,
            },
            bases=('indicators.stgindicator',),
        ),
        migrations.AddField(
            model_name='stgindicator',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicatorReference', verbose_name='Indicator Reference'),
        ),
        migrations.CreateModel(
            name='StgNarrative_TypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('shortname', models.CharField(max_length=120, null=True, unique=True, verbose_name='Short Name')),
                ('description', models.TextField(null=True, verbose_name='Brief Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.StgNarrative_Type')),
            ],
            options={
                'verbose_name': 'Narrative Type Translation',
                'db_table': 'stg_narrative_type_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=500, verbose_name='Indicator Name')),
                ('shortname', models.CharField(max_length=120, null=True, unique=True, verbose_name='Short Name')),
                ('definition', models.TextField(null=True, verbose_name='Indicator Definition')),
                ('preferred_datasources', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Primary Sources')),
                ('numerator_description', models.TextField(blank=True, null=True, verbose_name='Numerator Description')),
                ('denominator_description', models.TextField(blank=True, null=True, verbose_name='Denominator Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.StgIndicator')),
            ],
            options={
                'verbose_name': 'Indicator Translation',
                'db_table': 'stg_indicator_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorReferenceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='Global List of 100 Core Health Indicators', max_length=230, verbose_name='Reference Name')),
                ('shortname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.StgIndicatorReference')),
            ],
            options={
                'verbose_name': 'Indicator Reference Translation',
                'db_table': 'stg_indicator_reference_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgIndicatorDomainTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Theme')),
                ('shortname', models.CharField(max_length=45, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Brief Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='indicators.StgIndicatorDomain')),
            ],
            options={
                'verbose_name': 'Indicator Theme Translation',
                'db_table': 'stg_indicator_domain_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
