# Generated by Django 2.2.12 on 2021-03-18 09:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import indicators.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_auto_20201205_1938'),
        ('regions', '0015_stglocationcodes'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aho_factsindicator_archive',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('value_received', models.DecimalField(decimal_places=3, max_digits=20, null=True, verbose_name='Value')),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numerator Value')),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Denominator Value')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Minimum Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Maximum Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Target Value')),
                ('string_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='String Value')),
                ('start_period', models.IntegerField(default=2021, help_text='This Year marks the start of the reporting period', verbose_name='Starting Period')),
                ('end_period', models.IntegerField(default=2021, help_text='This Year marks the end of reporting.         The value must be current year or greater than the start year', verbose_name='Ending Year')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('comment', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Indicators Archive',
                'db_table': 'fact_data_archive',
                'ordering': ('indicator__name',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StgIndicatorNarrative',
            fields=[
                ('indicatornarrative_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code')),
                ('narrative_text', models.TextField(verbose_name='Narrative Text')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location')),
                ('narrative_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgNarrative_Type', verbose_name='Narrative Type')),
            ],
            options={
                'verbose_name': 'Indicator Narrative',
                'verbose_name_plural': 'Indicators Narrative',
                'db_table': 'stg_indicator_narrative',
                'ordering': ('-narrative_type',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StgAnalyticsNarrative',
            fields=[
                ('analyticstext_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Code')),
                ('narrative_text', models.TextField(verbose_name='Narrative Text')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('domain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicatorDomain', verbose_name='Theme')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location')),
                ('narrative_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgNarrative_Type', verbose_name='Narrative Type')),
            ],
            options={
                'verbose_name': 'Theme Narrative',
                'verbose_name_plural': 'Theme Narratives',
                'db_table': 'stg_analytics_narrative',
                'ordering': ('-narrative_type',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FactDataIndicator',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID')),
                ('numerator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numerator Value')),
                ('denominator_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Denominator Value')),
                ('value_received', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numeric Value')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Minimum Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Maximum Value')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Target Value')),
                ('string_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='String Value')),
                ('start_period', models.PositiveIntegerField(default=2021, help_text='This marks the start of reporting period', validators=[django.core.validators.MinValueValidator(1900), indicators.models.max_value_current_year], verbose_name='Starting period')),
                ('end_period', models.PositiveIntegerField(default=2021, help_text='This marks the end of reporting. The value must be current             year or greater than the start year', validators=[django.core.validators.MinValueValidator(1900), indicators.models.max_value_current_year], verbose_name='Ending Period')),
                ('period', models.CharField(blank=True, max_length=25, verbose_name='Period')),
                ('comment', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('categoryoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgCategoryoption', verbose_name='Disaggregation Options')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgDatasource', verbose_name='Data Source')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator Name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location Name')),
                ('measuremethod', models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='home.StgMeasuremethod', verbose_name='Measure Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)')),
            ],
            options={
                'verbose_name': 'Indicator Data Record',
                'verbose_name_plural': '    Single-record Form',
                'db_table': 'fact_data_indicators',
                'ordering': ('indicator__name',),
                'permissions': (('approve_factdataindicator', 'Can approve Indicator Data'), ('reject_factdataindicator', 'Can reject Indicator Data'), ('pend_factdataindicator', 'Can pend Indicator Data')),
                'managed': True,
                'unique_together': {('indicator', 'location', 'categoryoption', 'datasource', 'start_period', 'end_period')},
            },
        ),
    ]
