# Generated by Django 2.2.12 on 2021-03-18 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_aho_factsindicator_archive_factdataindicator_stganalyticsnarrative_stgindicatornarrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='measuremethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.StgMeasuremethod', verbose_name='Measure Type'),
        ),
    ]
