# Generated by Django 2.1.2 on 2020-12-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0025_auto_20201002_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factdataindicator',
            options={'managed': True, 'ordering': ('indicator__name',), 'permissions': (('approve_factdataindicator', 'Can approve Indicator Data'), ('reject_factdataindicator', 'Can reject Indicator Data'), ('pend_factdataindicator', 'Can pend Indicator Data')), 'verbose_name': 'Indicator Data Record', 'verbose_name_plural': '    Single-record Form'},
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='denominator_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Denominator Value'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Minimum Value'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='numerator_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numerator Value'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Target Value'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='value_received',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numeric Value'),
        ),
    ]
