# Generated by Django 2.1.2 on 2020-12-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0026_auto_20201205_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aho_factsindicator_archive',
            options={'managed': False, 'ordering': ('indicator__name',), 'verbose_name': 'Indicator Archive', 'verbose_name_plural': 'Indicators Archive'},
        ),
    ]
