# Generated by Django 2.1.2 on 2021-01-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0028_auto_20210128_0948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aho_factsindicator_archive',
            table='fact_data_archive',
        ),
    ]
