# Generated by Django 2.1.2 on 2021-02-03 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0030_auto_20210201_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factdataindicator',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='factdataindicator',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)'),
        ),
    ]
