# Generated by Django 2.1.2 on 2021-02-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0031_auto_20210203_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aho_factsindicator_archive',
            options={'managed': True, 'ordering': ('indicator__name',), 'verbose_name': 'Archive', 'verbose_name_plural': 'Indicators Archive'},
        ),
    ]
