# Generated by Django 2.1.2 on 2021-02-03 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20201205_1938'),
        ('regions', '0014_auto_20201024_0911'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0032_auto_20210203_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='aho_factsindicator_archive',
            name='categoryoption',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.PROTECT, to='home.StgCategoryoption', verbose_name='Disaggregation Option'),
        ),
        migrations.AddField(
            model_name='aho_factsindicator_archive',
            name='datasource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.StgDatasource', verbose_name='Data Source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aho_factsindicator_archive',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='indicators.StgIndicator', verbose_name='Indicator Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aho_factsindicator_archive',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aho_factsindicator_archive',
            name='measuremethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.StgMeasuremethod', verbose_name='Measure Type'),
        ),
        migrations.AddField(
            model_name='aho_factsindicator_archive',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)'),
        ),
        migrations.AddField(
            model_name='aho_factsindicator_archive',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='aho_factsindicator_archive',
            name='comment',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='aho_factsindicator_archive',
            name='denominator_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Denominator Value'),
        ),
        migrations.AlterField(
            model_name='aho_factsindicator_archive',
            name='end_period',
            field=models.IntegerField(default=2021, help_text='This Year marks the end of reporting.         The value must be current year or greater than the start year', verbose_name='Ending Year'),
        ),
        migrations.AlterField(
            model_name='aho_factsindicator_archive',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Maximum Value'),
        ),
        migrations.AlterField(
            model_name='aho_factsindicator_archive',
            name='numerator_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Numerator Value'),
        ),
        migrations.AlterField(
            model_name='aho_factsindicator_archive',
            name='start_period',
            field=models.IntegerField(default=2021, help_text='This Year marks the start of the reporting period', verbose_name='Starting Period'),
        ),
        migrations.AlterField(
            model_name='aho_factsindicator_archive',
            name='string_value',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='String Value'),
        ),
        migrations.AlterField(
            model_name='aho_factsindicator_archive',
            name='value_received',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True, verbose_name='Value'),
        ),
    ]
