# Generated by Django 2.2.12 on 2021-03-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stghealthworkforcefacts',
            old_name='cadre_id',
            new_name='cadre',
        ),
    ]
