# Generated by Django 2.1.2 on 2020-07-28 06:05

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0009_auto_20200727_2255'),
        ('publications', '0007_stgresourcetypetranslation_categorization'),
        ('health_workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgInstitutionType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
            ],
            options={
                'verbose_name': 'Institution Type',
                'verbose_name_plural': 'Institution Types',
                'db_table': 'stg_institution_type',
                'ordering': ('code',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgInstitutionTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Resource Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='health_workforce.StgInstitutionType')),
            ],
            options={
                'verbose_name': 'Institution Type Translation',
                'db_table': 'stg_institution_type_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgTrainingInstitution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID')),
                ('code', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Location Code')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('location', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Location')),
                ('type', models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='health_workforce.StgInstitutionType', verbose_name='Economic Block')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Training Institutions',
                'db_table': 'stg_traininginstitution',
                'ordering': ['code'],
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgTrainingInstitutionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Location Name')),
                ('programmes', models.TextField(blank=True, null=True, verbose_name='Training Programs')),
                ('level', models.CharField(max_length=150, verbose_name='Education Level')),
                ('accreditation', models.CharField(max_length=200, verbose_name='Accreditation Status')),
                ('language', models.CharField(max_length=50, verbose_name='Teaching Language')),
                ('address', models.CharField(max_length=500, verbose_name='Contact Address')),
                ('posta', models.CharField(blank=True, max_length=500, verbose_name='Postal Address')),
                ('email', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Email Address')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='health_workforce.StgTrainingInstitution')),
            ],
            options={
                'verbose_name': 'Institution Translation',
                'db_table': 'stg_traininginstitution_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HumanWorkforceResourceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Resource & Guide',
                'verbose_name_plural': ' Resources & Guides',
                'proxy': True,
                'indexes': [],
            },
            bases=('publications.stgknowledgeproduct',),
        ),
        migrations.AlterModelOptions(
            name='resourcetypeproxy',
            options={'verbose_name': 'Resource Type', 'verbose_name_plural': ' Resource Types'},
        ),
        migrations.AlterUniqueTogether(
            name='stgtraininginstitutiontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='stginstitutiontypetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
