# Generated by Django 2.1.2 on 2020-07-28 07:41

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_auto_20200728_0757'),
        ('regions', '0009_auto_20200727_2255'),
        ('health_workforce', '0002_auto_20200728_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='StgHealthWorkforceFacts',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Unique Universal ID')),
                ('code', models.CharField(blank=True, max_length=45, unique=True, verbose_name='ISCO-08 Code')),
                ('status', models.CharField(choices=[('pending', 'Active'), ('approved', 'Inactive')], default='pending', max_length=10, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_lastupdated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.StgHealthFacility', verbose_name='Affliation')),
            ],
            options={
                'verbose_name': 'Healthworkforce Data',
                'verbose_name_plural': '  Healthworkforce Data',
                'db_table': 'fact_health_workforce',
                'ordering': ('code',),
                'managed': True,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StgHealthWorkforceFactsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=230, verbose_name='Cadre (Occupation) Name')),
                ('shortname', models.CharField(default='Not Available', max_length=230, verbose_name='Cadre Short Name')),
                ('academic', models.CharField(blank=True, max_length=500, null=True, verbose_name='Qualification Level')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='health_workforce.StgHealthWorkforceFacts')),
            ],
            options={
                'verbose_name': 'Healthworkforce Data Translation',
                'db_table': 'fact_health_workforce_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='stgtraininginstitutiontranslation',
            name='accreditation_info',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Accreditation Status'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitution',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Geographical Location'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitution',
            name='type',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='health_workforce.StgInstitutionType', verbose_name='Institution Type'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitutiontranslation',
            name='accreditation',
            field=models.CharField(choices=[('accredited', 'Accredited'), ('charterted', 'Chartered'), ('unacredited', 'Not Accredited'), ('pending', 'Pending Accreditation')], default='accredited', max_length=50, verbose_name='Accreditation Status'),
        ),
        migrations.AddField(
            model_name='stghealthworkforcefacts',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_workforce.StgTrainingInstitution', verbose_name='Highest Institution'),
        ),
        migrations.AddField(
            model_name='stghealthworkforcefacts',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.StgLocation', verbose_name='Geographical Location'),
        ),
        migrations.AlterUniqueTogether(
            name='stghealthworkforcefactstranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
