# Generated by Django 2.2.12 on 2021-03-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0002_auto_20210318_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stghealthworkforcefacts',
            options={'managed': True, 'ordering': ('cadre',), 'verbose_name': 'Health Workforce', 'verbose_name_plural': '    Health Workforce'},
        ),
        migrations.RenameField(
            model_name='stgrecurringevent',
            old_name='cadre_id',
            new_name='cadre',
        ),
    ]
