# Generated by Django 2.1.2 on 2020-07-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0003_auto_20200728_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='stginstitutiontypetranslation',
            name='shortname',
            field=models.CharField(blank=True, max_length=230, null=True, verbose_name='Short Name'),
        ),
    ]
