# Generated by Django 2.1.2 on 2020-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0004_stginstitutiontypetranslation_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stghealthworkforcefacts',
            name='aggregation_type',
            field=models.CharField(choices=[('Count', 'Count'), ('Sum', 'Sum'), ('Average', 'Average'), ('Standard Deviation', 'Standard Deviation'), ('Variance', 'Variance'), ('Min', 'Min'), ('max', 'max'), ('None', 'None')], default='Count', max_length=45, verbose_name='Data Aggregation'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitution',
            name='code',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Institution Code'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitutiontranslation',
            name='accreditation_info',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Accreditation Details'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitutiontranslation',
            name='level',
            field=models.CharField(max_length=150, verbose_name='Highest Academic Level'),
        ),
    ]
