# Generated by Django 2.1.2 on 2020-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0017_auto_20201024_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stghealthworkforcefacts',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Data Value'),
        ),
        migrations.AlterField(
            model_name='stgtraininginstitutiontranslation',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='Email'),
        ),
    ]
