# Generated by Django 2.1.2 on 2021-02-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_workforce', '0019_auto_20210128_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stghealthworkforcefacts',
            options={'managed': True, 'ordering': ('cadre_id',), 'verbose_name': 'Health Workforce', 'verbose_name_plural': '    Health Workforce'},
        ),
    ]
