# Generated by Django 2.1.2 on 2021-02-03 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_workforce', '0020_auto_20210203_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='stghealthworkforcefacts',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)'),
        ),
    ]
