# Generated by Django 2.1.2 on 2021-02-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_stgknowledgeproduct_user'),
        ('health_workforce', '0022_stgtraininginstitution_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'proxy': True,
                'indexes': [],
            },
            bases=('publications.stgresourcecategory',),
        ),
    ]
