# Generated by Django 2.1.2 on 2020-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201024_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stgcategoryoption',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
