# Generated by Django 2.2.12 on 2021-03-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_auto_20210315_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgresourcecategory',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Research Products'), (2, 'Health Workforce')], default=1, verbose_name='Classification'),
        ),
    ]
