# Generated by Django 2.2.12 on 2021-03-18 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0021_stgresourcecategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stgknowledgeproduct',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Name (Email)'),
        ),
    ]
